### ISSUE TITLE
only 2050 characters?

### ISSUE THREAD

**Issue by gitTinker** [xorbit/PoE-FeatherWing-demos#1]
@xorbit I found a limitation, can only send up to 2050 characters, using the [PoE-FeatherWing](https://www.amazon.com/gp/product/B08KTVD7BR).

I [made a workaround](https://github.com/khoih-prog/EthernetWebServer_SSL/issues/6#issuecomment-855472514), so there is no failure/issue.

However, can you think of any reason the 2050 char limits is there?

Note: while the workaround is to the library I prefer to use, the limitation exists when using the [native Arduino library ](https://www.arduino.cc/en/Reference/Ethernet)too, and the example attached has workaround commented-out

[Arduino-WebServer_bufferTest.ino.txt](https://github.com/xorbit/PoE-FeatherWing-demos/files/6605115/Arduino-WebServer_bufferTest.ino.txt)
[index_complete_html.h.txt](https://github.com/xorbit/PoE-FeatherWing-demos/files/6605116/index_complete_html.h.txt)
[index_html.h.txt](https://github.com/xorbit/PoE-FeatherWing-demos/files/6605117/index_html.h.txt)
[index_html2.h.txt](https://github.com/xorbit/PoE-FeatherWing-demos/files/6605118/index_html2.h.txt)

I do not observe the same limitation when using an ESP8266.

**Comment by gitTinker** [comment]
@xorbit see [Khoi's comment](https://github.com/khoih-prog/EthernetWebServer_SSL/issues/6#issuecomment-855541017). The 2K limitation is part of the base Ethernet library.

Closing issue as it is not a PoE-FeatherWing problem; it is a library problem.

**Comment by xorbit** [comment]
Alright, thank you for letting me know.
I have noticed a lot of software limitations with the various "maker level" drivers for the W5500, I have been spending a lot of time myself on improving the CircuitPython driver which was very limited.
