### ISSUE TITLE
Advanced Example

### ISSUE THREAD

**Issue by gitTinker** [xorbit/PoE-FeatherWing-demos#2]
@xorbit  I was able to use the POE-Featherwing for more than the basic examples.
Thanks for a great solution to build on!

Should anyone need [an example](https://github.com/LaudixGit/SAMD51_5500_Neopixel_Websocket_Demo) using the built-in MAC and with large (> 2k) pages.

**Comment by gitTinker** [comment]
Closing since this is information sharing, **not** an issue

**Comment by xorbit** [comment]
Thank you @gitTinker!  I will try to add this example to the README when my vacation is over.
